### PR TITLE
Update grammar to support '.' in keys

### PR DESCRIPTION
**Pull request by mathstuf**
---

CC: @linus-sherrill

### CODE REVIEW

**Comment by mathstuf** [comment]
No idea why github thinks the merge commit (which *is* master) is part of this pull request…

**Comment by mathstuf** [comment]
Hmm. Something is pushing master back to before the merge. @bradking is kwrobot doing something here? Where is it pulling from?

**Comment by bradking** [comment]
There is currently a mirror robot operation from git://sprokit.org/sprokit.git to here.  If you're switching development to this Github repo I will disable the mirror.

**Comment by mathstuf** [comment]
Ah. I remember this being the plan; just had never set up the proper remotes.

**Pull request merged**
